export const introConfig = {
  cssVars: {
    contentMax: '112.5rem',
    pageGutter: 'clamp(1rem, 2.3vw, 2.5rem)',
    navHeight: 'clamp(3.5rem, 5vw, 4.75rem)',
    navPillHeight: 'clamp(2.25rem, 3vw, 2.5rem)',
    stageMax: '92rem',
    stageHeight: 'min(68svh, 44rem)',
    stageRadius: '1.375rem',
    cardWidth: 'clamp(10rem, 16vw, 18.5rem)',
  },
  pointerTrail: {
    poolSize: 8,
    spawnThreshold: 95,
    minSpawnMs: 48,
    progressCutoff: 0.85,
  },
  timeline: {
    pinDistance: '+=340%',
    depthEnd: 0.3,
    disperseStart: 0.1,
    disperseDuration: 0.42,
    fadeStart: 0.68,
    fadeDuration: 0.14,
    textRevealStart: 0.74,
    textRevealDuration: 0.16,
    textHoldStart: 0.86,
    textHoldDuration: 0.14,
    chromeFadeStart: 0.58,
    chromeFadeDuration: 0.2,
    introFadeStart: 0.5,
    introFadeDuration: 0.18,
    scrollLabelFadeStart: 0.48,
    scrollLabelFadeDuration: 0.18,
    scrollLabelOffset: 12,
    scatterMultiplier: 1.35,
  },
};
