export const introConfig = {
  cssVars: {
    contentMax: '112.5rem',
    pageGutter: 'clamp(1rem, 2.3vw, 2.5rem)',
    navHeight: 'clamp(3.5rem, 5vw, 4.75rem)',
    navPillHeight: 'clamp(2.25rem, 3vw, 2.5rem)',
    stageMax: '92rem',
    stageHeight: 'min(68svh, 44rem)',
    stageRadius: '1.375rem',
    cardWidth: 'clamp(11rem, 18vw, 21rem)',
  },
  pointerTrail: {
    poolSize: 7,
    spawnThreshold: 220,
    minSpawnMs: 120,
    progressCutoff: 0.85,
  },
  timeline: {
    pinDistance: '+=430%',
    depthEnd: 0.3,
    disperseStart: 0.1,
    disperseDuration: 0.42,
    fadeStart: 0.54,
    fadeDuration: 0.16,
    textRevealStart: 0.78,
    textRevealDuration: 0.14,
    chromeFadeStart: 0.5,
    chromeFadeDuration: 0.18,
    blackStart: 0.56,
    blackDuration: 0.14,
    imageRevealStart: 0.64,
    imageRevealDuration: 0.12,
    imageSettleStart: 0.72,
    imageSettleDuration: 0.14,
    scrollLabelFadeStart: 0.48,
    scrollLabelFadeDuration: 0.18,
    scrollLabelOffset: 12,
    scatterMultiplier: 1.5,
  },
};
