export const introConfig = {
  cssVars: {
    contentMax: '112.5rem',
    pageGutter: 'clamp(1rem, 2.3vw, 2.5rem)',
    navHeight: 'clamp(3.5rem, 5vw, 4.75rem)',
    navPillHeight: 'clamp(2.25rem, 3vw, 2.5rem)',
    stageMax: '92rem',
    stageAspect: '18 / 9',
    stageAvailableHeight: 'calc(100svh - var(--nav-height) - var(--page-gutter) * 3 - 2rem)',
    stageRadius: '1.375rem',
    cardWidth: 'clamp(10.4rem, 17.6vw, 20.8rem)',
  },
  pointerTrail: {
    poolSize: 10,
    visibleLimit: 5,
    spawnThreshold: 220,
    minSpawnMs: 120,
    progressCutoff: 0.85,
  },
  timeline: {
    pinDistance: '+=430%',
    depthEnd: 0.3,
    disperseStart: 0.1,
    disperseDuration: 0.42,
    fadeStart: 0.54,
    fadeDuration: 0.16,
    chromeFadeStart: 0.5,
    chromeFadeDuration: 0.18,
    scrollLabelFadeStart: 0.48,
    scrollLabelFadeDuration: 0.18,
    scrollLabelOffset: 12,
    scatterMultiplier: 1.5,
  },
};
